### ISSUE TITLE
URL Dead

### ISSUE THREAD

**Issue by 11galpid** [waldo-irc/ArmPi#1]
Hey, the project looks amazing and Id like to use it, any chance you could re-upload the img?
Thanks

**Comment by waldo-irc** [comment]
Image has been re-uploaded.  It's important to keep in mind I haven't maintained this package in 2 years so it may not work at this point on OSX Catalina for example and newer Ubuntu/Windows versions.  If there's any issues please open another ticket and I'll take care of it.  I'll look into maintaining this again more frequently.

**Comment by 11galpid** [comment]
I tried downloading it several times, I get an error with the CRC, could you possibly re-upload? thank you and sorry for the hassle

**Comment by waldo-irc** [comment]
what was the error?  I'm not having issues on my end?

**Comment by 11galpid** [comment]
Archive corrupt when trying to extract .img file, it opens correctly for you?
Ill try to download again from some server to confirm, might be just a failure on my end

**Comment by waldo-irc** [comment]
Actually ya I lied, it's a bad hash, I'll re upload it later today.

**Comment by waldo-irc** [comment]
Ok it should be fixed, sorry for the delay.
